# Generated by Django 2.2 on 2019-04-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='published')),
            ],
        ),
    ]
