# Generated by Django 2.2 on 2019-04-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
